# organize configuration file
# https://organize.readthedocs.io

rules:
  - name: "Delete files from ~/Downloads"
    locations:
      - ~/Downloads
    subfolders: false
    filters:
      - extension:
          - pdf
          - dmg
          - png
          - jpg
          - epub
          - mobi
          - txt
      - name
    actions:
      - confirm: "Delete {name}"
      - trash

